### PR TITLE
Fallback to current date if SKPaymentTransaction#getTransactionDate() is null

### PR DESCRIPTION
**Pull request by prineside**
Resolves libgdx/gdx-pay#240

### CODE REVIEW

**Review by MrStahlfelge — APPROVED** [review]
LGTM, let's see if someone else chimes in or if @keesvandieren wants to comment

**Comment by prineside** [comment]
Oh, import is missing - did not notice that. Will fix asap

**Comment by keesvandieren** [comment]
Apart from missing import, it looks good. I have iOS apps which have either subscriptions or in-app purchases (non-consumables), and I don't have this issue.

* What kind of in-app purchases do you have? (subscriptions, consumables, non-consumables)?
* are you using "App Store Promotion" for in-app-store purchases? I don't have that, but that is a different flow, maybe that is causing it?
* Is it a specific country, or specific device-type it happens to?

**Comment by prineside** [comment]
> Apart from missing import, it looks good. I have iOS apps which have either subscriptions or in-app purchases (non-consumables), and I don't have this issue.
> 
> * What kind of in-app purchases do you have? (subscriptions, consumables, non-consumables)?
> * are you using "App Store Promotion" for in-app-store purchases? I don't have that, but that is a different flow, maybe that is causing it?
> * Is it a specific country, or specific device-type it happens to?

Consumables and non-consumables. No subscriptions / promotions.
We've received reports from 25 different users but, unfortunately, I don't know their device model / iOS version / country.
I'll try to collect this data with the next update

**Comment by prineside** [comment]
> * Is it a specific country, or specific device-type it happens to?

User regions: US / AU / GB
CPU: Apple A9 / A10 / A13
Device: iPhone / iPadOS: 14.0.1 / 14.4 / 14.5
Languange: en
RoboVM version: 2.3.12

I've only received 3 reports till this moment, not sure if it is related to iOS 14

**Pull request merged**
