### PR TITLE
#198 added synchronized block to instantiation and strong-ref management

### PR DESCRIPTION
**Pull request by keesvandieren**
Hi @MrStahlfelge , I think we need to synchronize instantiation and strongref management.

I was not able to reproduce the problem (as it happens only for 1-2% of our users), but based on reasoning of code, I think this patch may solve the problem.

Can you review the PR? Thanks in advance.

### CODE REVIEW

**Comment by MrStahlfelge** [comment]
Yes it could be a solution. Do you want to test this on an own build before merging to master?

**Comment by keesvandieren** [comment]
I’ve verified that the app launches without problems. 

I will run a test for a week, and see if it solves the crash, if we want to be really sure it helps?

**Comment by MrStahlfelge** [comment]
That's a good plan, let's do it this way. Please comment again then. :)

**Comment by MrStahlfelge** [comment]
Closing it because it doesn't fix #198

**Pull request closed without merging**
