### PR TITLE
Fix #251 support free trial period with NON_RECURRING cycle

### LINKED ISSUE #251: Free trial no longer detected on Android
Please ensure you have given all the following requested information in your report.

#### Issue details, reproduction steps/code
We found that the free trial offering in Google Play for subscriptions is no longer detected 

#### Version of gdx-pay and/or relevant dependencies
1.3.3

#### Stacktrace
```java
n/a
```

#### Please select the affected platforms and payment service implementation
- [ x] googlebilling

Fixed the bug, creating issue for PR

### PR DESCRIPTION
**Pull request by keesvandieren**
Google Play Services is now using different parameters to share free trials.

Added support for the new parameter set, also kept supporting the old one

Can anyone using subscriptions review the change?

### CODE REVIEW

**Comment by keesvandieren** [comment]
Hi, anyone willing to review? I have already verified it in production. 

I will merge it soon if nobody has any obligations.

**Comment by Mostafa1695** [comment]
Hello @keesvandieren! Thanks a lot for fixing this issue. I've also verified that its working in my app.
Would be great if you can merge and make a new release when you have the time please 🙇‍♂️

**Comment by keesvandieren** [comment]
@Mostafa1695 release has been completed and is available in maven central

**Comment by Mostafa1695** [comment]
Perfect, thank you!

**Pull request merged**
