### PR TITLE
PurchaseManager for HUAWEI App Gallery

### PR DESCRIPTION
**Pull request by FStranieri**
This is a new PurchaseManager to manage the HUAWEI App Gallery purchases.
It checks if the app environment is ready to manage those kind of purchases and then it fetch all pricetypes (consumable, entitlement and subscriptions).
It also provides a public method to consume a consumable product.
With this manager, the developer has to implement the callbacks and manage the results. 
It's very easy to integrate.

Thank you.

Regards,
Francesco Stranieri

### CODE REVIEW

**Comment by keesvandieren** [comment]
Hi,

Thanks for your contribution! Can you please provide following updates:

* look at codebeat issues, and solve their reported issues if appropriate.
* provide a README.md with instructions how to use it.

**Comment by FStranieri** [comment]
> Hi,
> 
> Thanks for your contribution! Can you please provide following updates:
> 
> * look at codebeat issues, and solve their reported issues if appropriate.
> * provide a README.md with instructions how to use it.

Done!
For the codebeat issues I've operated some changes.

Thank you!

**Comment by MrStahlfelge** [comment]
Hi, thanks for the contribution. 

Code looks good to me.

Unfortunately, I can't test it because I don't have an Huawei account, so I'd just want to ask if you have tested the implementation against our example application project. This is important to see if there are any quirks in the implementation that are hidden by your own game project.

**Comment by FStranieri** [comment]
> Hi, thanks for the contribution.
> 
> Code looks good to me.
> 
> Unfortunately, I can't test it because I don't have an Huawei account, so I'd just want to ask if you have tested the implementation against our example application project. This is important to see if there are any quirks in the implementation that are hidden by your own game project.

Hi, thank for the suggestion!
I've forked the gdx-pay-app and added a test for HuaweiPurchaseManager [link](https://github.com/FStranieri/gdx-pay-example).
I've discovered 3 regressions caused to the enhancement for codebeats.
It works with all tests included into the app (install, productInfo, purchase of entitlement and consumable (i support subscription too) and the restore).

Screens:

Screenshot_20200512_003558_com badlogic gdx pay app
Screenshot_20200512_011940_com badlogic gdx pay app

**Comment by MrStahlfelge** [comment]
Thanks! @keesvandieren do you see any reason not to merge this?

**Comment by keesvandieren** [comment]
I think it is fine to merge this 👍🏼

Hartelijke groeten,

Kees van Dieren
Oranjestraat 30
2983HS Ridderkerk
📞+31 (0) 6-30413841

Op di 12 mei 2020 17:57 schreef Benjamin Schulte <notifications@github.com>:

**Comment by FStranieri** [comment]
Thank you!
What about the artifact on maven central?
Thanks.

Regards,
Francesco Stranieri

**Comment by MrStahlfelge** [comment]
1.2-SNAPSHOT is updated, tell me if there's a problem

**Comment by FStranieri** [comment]
Schermata 2020-05-12 alle 19 49 41

It works!
Thanks.

**Comment by FStranieri** [comment]
Hi, are you planning a new stable release? @MrStahlfelge @keesvandieren 
Thank you

**Comment by MrStahlfelge** [comment]
Yes it is needed because of the Google Play change too. @keesvandieren do you already use the snapshot in production?

**Comment by keesvandieren** [comment]
I'm using version 1.1.0 of gdx-pay-android-googlebilling, and that version is working fine for me. We are using subscriptions.

What is the change needed on Google Play? Is Google Billing 1.x going end of life?

**Comment by MrStahlfelge** [comment]
Yes, April 2021 is the switch-off of 1.x and AIDL

**Comment by keesvandieren** [comment]
Aha ok. Currently it is a bit dangerous to try things out on Google Play. Currently app-updates take about one week:

image

I prefer to try it out, when Google app-updates  scheme is 'back to normal'. Hopefully coming soon, as covid-19 is calming down a bit?

Has anybody else already tried it out?

**Comment by MrStahlfelge** [comment]
I use it in a non-libgdx app without gdx-pay in the same way it is implemented here, so I am expecting no problems. 

As far as I am concerned, Google Play wait times are back to normal. Google Billing 3.0.0 is already out, so I think we should make a new release soon.

**Comment by keesvandieren** [comment]
Releasing is fine to me as well now.

We're using snapshot as of now, and it seems to work well.

We're considering to add more features (related to subscriptions), but that can also be added to a subsequent release, as it may take time.

**Comment by MrStahlfelge** [comment]
Release is done. :-)

**Pull request merged**
