### PR TITLE
Added consuming products on restore - Huawei.

### PR DESCRIPTION
**Pull request by Berobasket**
There was a problem when consumable products was not consumed when restoring transaction. User was not able to buy consumed products because of "already owned error". There was no way to consume product. Now consumable products are consumed when restoring. The same behaviour is adopted in google billing.

### CODE REVIEW

**Comment by Berobasket** [comment]
@FStranieri I did it the same way as you in method onActivityResult() in case OrderStatusCode.ORDER_STATE_SUCCESS. So - these two places needs to change?

**Comment by Berobasket** [comment]
I made another commit - https://github.com/Berobasket/gdx-pay/commit/08301616eb1b3bc73e55687590385e680e400cae @FStranieri could you check if it is ok now?

**Comment by FStranieri** [comment]
For me It's OK! 
Thanks!

**Comment by MrStahlfelge** [comment]
Best is if you open another PR

**Pull request merged**
