### PR TITLE
Expose precise price to clients

### PR DESCRIPTION
**Pull request by jstuyts**
Added price (as double) to the information object. Changed providers to also fill this field (if the information is available). Deprecated the price in cents as it is not precise enough for some currencies

### CODE REVIEW

**Comment by noblemaster** [comment]
Cents isn't meant to be a factor of `0.01`. Rather, it's supposed to mean the lowest possible value for a currency. I think looking at the code, you are correct that multiplying by 100 isn't correct. We should fix that!

That said, I don't think adding a float/double is the way to go. Having a value of 1.0 still doesn't tell me if we have a `1`, `1.00`, `1.000` etc. I think rather the developer should show the text string for the value. Otherwise, we could also add a currency class which tells how many digits are there (if the currency code is known?).

Example Currency Class: [Currency.java](https://github.com/TakahikoKawasaki/nv-i18n/blob/master/src/main/java/com/neovisionaries/i18n/CurrencyCode.java)

**Comment by jstuyts** [comment]
I need the numeric value to calculate discount percentages and prices per shortest subscription unit (e.g. € 2.87 per month), so my customers can make an informed decision when presented with multiple options. If I cannot calculate them based on information returned by the stores, I would have to hard-code the discounts and monthly prices for each offering. Then I cannot change the prices without having to make a new app release, and having to time the pricing changes in the stores and the app releases very carefully.

The currency formatter and currency classes which are part of the JDK, should format a price with the correct number of fraction. The only issue I found with those is that the JDK seems to prefer the currency code instead of the symbol. This will result in the following information being shown for a yearly subscription for example:

* Price string returned by gdx-pay: € 19.99 per year
* Monthly price calculated based on duration of subscription, and formatted with standard JDK formatter: (EUR 1.67 per month)

**Comment by noblemaster** [comment]
That make sense, but it does solve the problem very well because you don't know the number of fraction digits. It doesn't tell you how to format the number. There are no fraction digits for Japanese, so if it's `JPY 1999`, and you divide by 12, you will get `JPY 166.58` which is wrong. It should be `JPY 167`. Customers will be reluctant to buy if you aren't able to properly express the number in their currency. 

We should have given an e.g. `priceInCentsFactor` that gives a factor of e.g. `100` for EUR/USD and `1` for JPY. Or `priceInCentsDigits` or similar.

**Comment by jstuyts** [comment]
The formatter, locale and currency classes of the run-time environment make sure that prices are displayed properly to the user. So in your example, these classes will generate `JPY 167` for 166.58.

If your run-time environment does not have these types of classes, then you should use another source for information about the number of fraction digits for a specific currency.

I don't see the point of having gdx-pay convert the actual price to a representation in the smallest unit for a currency, only for me to undo that conversion so I can use the standard JDK classes to format it for display. For example for € 1.23:

* gdx-pay converts it to: 123.
* I convert it to back to: 1.23, so I can use the standard JDK classes to display the price.

**Pull request merged**
