### PR TITLE
Allow more then 20 SKUs

### PR DESCRIPTION
**Pull request by B4dT0bi**
This will solve issue #144

### CODE REVIEW

**Comment by B4dT0bi** [comment]
Sorry missed to commit this part, committed it now.
Test are not failing anymore.

**Comment by B4dT0bi** [comment]
Should I also update the wrong dependencies? Or will you do it?

**Comment by keesvandieren** [comment]
Which libraries? Are some dependencies outdated? I will update robovm
dependencies for iOS client. I will work on that tomorrow.

Op 18 apr. 2017 23:40 schreef "B4dT0bi" <notifications@github.com>:

**Comment by keesvandieren** [comment]
Just pushed several library upgrades, will continue tomorrow.

**Comment by keesvandieren** [comment]
I have just published new snapshots to https://oss.sonatype.org/content/repositories/snapshots

Would be great if you could give them a try

**Comment by B4dT0bi** [comment]
Sorry, didnt had time till now.
I tested it now and it looks good.

thanks and regards, 
Tobi

**Comment by keesvandieren** [comment]
Thanks for testing! Its released now in v0.11.0, no longer need to use snapshots.

**Pull request merged**
