### PR TITLE
added additional info about required Paid Apps agreement

### PR DESCRIPTION
**Pull request by LeftHandFreeStudio**

### CODE REVIEW

**Comment by MrStahlfelge** [comment]
Hi, there's a typo. :)

**Comment by MrStahlfelge** [comment]
Closing this, no reaction.

**Comment by LeftHandFreeStudio** [comment]
Hello @MrStahlfelge! If you think that there is still point in merging this, could you point me where the typo is?  Then I could fix this.

**Comment by MrStahlfelge** [comment]
actuall

**Comment by LeftHandFreeStudio** [comment]
fixed

**Pull request merged**
